name: CI-CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Angular CLI
        run: npm install -g @angular/cli@13

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Angular build
        run: npm run build --if-present

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest

      - name: Deploy container on self-hosted GH Runner
        run: |
          docker stop todo-container || true
          docker rm todo-container || true
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest
          docker run -d --name todo-container -p 8080:80 ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest
